// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjENQ0pbUUrd3ecahG7-qmHz4rce9TxWg',
    appId: '1:431782026620:android:53ce8d42c83ee5d27898f9',
    messagingSenderId: '431782026620',
    projectId: 'todo-list-b8f19',
    storageBucket: 'todo-list-b8f19.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNfwmz_vErP6gotEEK4zg94Aw3qNJRCIE',
    appId: '1:431782026620:ios:ae79ed393b7d34b77898f9',
    messagingSenderId: '431782026620',
    projectId: 'todo-list-b8f19',
    storageBucket: 'todo-list-b8f19.appspot.com',
    androidClientId: '431782026620-c7vo8p01cij2kgji07o0ujscqbtlpeq8.apps.googleusercontent.com',
    iosClientId: '431782026620-qlvef5bh185r1tngafp5etoikievmvvi.apps.googleusercontent.com',
    iosBundleId: 'br.com.albinomoreira.todoList',
  );
}
